### ISSUE TITLE
Navbar - changing height

### ISSUE THREAD

**Issue by tgs-1** [Servoy/bootstrapextracomponents#31]
How can I set the height of the navbar?
When I am changing the size property, it doesn't change on the NG Client in the browser.

**Comment by paronne** [comment]
Hi, the height of the navbar is indeed fixed; therefore if you resize it's container indeed it doesn't change height. This is done so that all it's inner elements are nicely centered vertically.

If you wish to change the height of the Navbar you can do it using the CSS styleSheet of the solution, modifying the height of the Navbar and the height/padding/margin of it's inner elements.

Regards,
Paolo
