### ISSUE TITLE
Progress Bars not rendering in 8.2

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/bootstrapextracomponents#7]
I tried to use them in 8.2 pre-release and they didn't render. I also ran the demo solution as-is and same result.
Looks like rating might have same result too

**Comment by pruhsert** [comment]
That's an ugly one. 8.2 upgrade angular and along with that, upgraded angular-ui. Between the version 8.1 used and the new version used in 8.2 there has been a change in the naming of elements

https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

So formerly the element was <progressbar> and now it needs to be <uib-progressbar>. So what goes wrong here is that basically the directive doesn't pick this up.

Not sure how to deal with that. We might have to ship two versions for a while. Carousel and Rating are also affected, because they are both based on angular-ui.

**Comment by paronne** [comment]
We need to branches indeed. Bootstrapcomponents and svyExtra already have a svy81x branch and a master branch which is updated to 8.2

**Comment by pruhsert** [comment]
that should be fixed with the 8.2 release
